spring.application.name=deucalint-platform
server.port=8080
spring.codec.max-in-memory-size=512KB
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=25s
