import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
await fs.mkdir('docs/media',{recursive:true});
const browser=await chromium.launch();
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'.data/recordings',size:{width:1440,height:1000}}});
const page=await context.newPage();
await page.goto('http://127.0.0.1:8100/');
await page.getByRole('button',{name:'Enter workspace'}).click();
await page.getByText('Traffic & engagement').waitFor();
await page.screenshot({path:'docs/media/overview.png',fullPage:true});
await page.waitForTimeout(2000);
await page.getByRole('button',{name:'Investigate changes'}).click();
await page.getByText('Investigation findings').waitFor();
await page.screenshot({path:'docs/media/investigation.png',fullPage:true});
await page.waitForTimeout(2000);
await page.getByRole('button').filter({hasText:'Conversion comparison'}).click();
await page.waitForTimeout(1500);await page.getByLabel('Close evidence').click();
await page.getByRole('link',{name:'Funnels',exact:false}).click();await page.getByRole('heading',{name:'Purchase journey'}).waitFor();await page.waitForTimeout(2000);
await page.getByRole('link',{name:'Demo commerce'}).click();await page.getByRole('button',{name:'Enable tracking'}).waitFor();
await page.screenshot({path:'docs/media/demo-store.png',fullPage:true});await page.waitForTimeout(2000);
const video=page.video();await context.close();await video.saveAs('docs/media/walkthrough.webm');await browser.close();
console.log('Saved desktop screenshots and walkthrough to docs/media.');
